---
title: "Chelsey's Fisheries Analysis"
author: "Chelsey"
date: "5/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library (here)
library(janitor)
library(paletteer) #installed
```
```{r}
us_landings <- read_csv(here("data","noaa_landings.csv"), na ="no data") 
```
```{r}
salmon_clean <- us_landings %>%
  clean_names() %>% #makes headers snake case
mutate(afs_name = str_to_lower(afs_name)
       )%>% #make fish lowercase
   mutate(dollars_num = parse_number(dollars_usd)) %>% 
  filter(str_detect(afs_name, pattern = "salmon"))%>% #only salmon
  separate(afs_name,into= c("group","subgroup"), sep=", ")%>% #separate subgroups
 drop_na(dollars_num)
  
```
```{r}
salmon_us_annual <- salmon_clean %>%
  group_by(year,subgroup)%>%
   summarise(tot_value = sum(dollars_num, na.rm = TRUE))
```
```{r}
salmon_us_annual <- salmon_clean %>% 
  group_by(year, subgroup)
```
```{r}
library(tidyverse)
library (here)
library(janitor)
library(paletteer)
```
```{r}
salmon_us_annual <- salmon_clean %>% 
  group_by(year,subgroup)%>%
  summarise(total_dollars= sum(dollars_num, na.rm=TRUE),)

```
```{r}
salmon_gg <- ggplot(salmon_us_annual, aes(x=year,y=total_dollars, group=subgroup))+ geom_line(aes(color=subgroup))+theme_bw()+labs(x="year",y="US commercial salmon value (USD")+ scale_color_paletteer_d("ggthemes::Hue Circle")

salmon_gg
```
```{r}
library(kableExtra)
kable(salmon_us_annual)
```